### ISSUE TITLE
Failed to install genromfs dependency

### ISSUE THREAD

**Issue by dogmaphobic** [PX4/homebrew-px4#25]
macOS 10.13.3
Install Homebrew from scratch
```
$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
$ brew tap PX4/px4
```
Now install px4-dev:
```
$ brew install px4-dev
==> Installing px4-dev from px4/px4
==> Installing dependencies for px4/px4/px4-dev: git, bash-completion, gcc-arm-none-eabi, genromfs, xz, autoconf, automake, libtool, pkgconfig, kconfig-frontends, astyle, cmake, ninja, ant, fastrtps, fastcdr
```
It then proceeds to install the dependencies. It fails when it reaches `genromfs`:

```
==> Installing px4/px4/px4-dev dependency: genromfs
==> Downloading http://px4-travis.s3.amazonaws.com/toolchain/genromfs-0.5.2.tar.
######################################################################## 100.0%
Error: uninitialized constant #<Class:0x007f8dbc91b0f8>::DATA
Did you mean?  Data
               Date
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Taps/px4/homebrew-px4/genromfs.rb:15:in `patches'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1904:in `prepare_patches'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1094:in `block in brew'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1895:in `block (2 levels) in stage'
/usr/local/Homebrew/Library/Homebrew/utils.rb:556:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1894:in `block in stage'
/usr/local/Homebrew/Library/Homebrew/resource.rb:119:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:73:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:73:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:73:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:12:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:114:in `unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:92:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1872:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1092:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:111:in `block in install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:556:in `with_env'
/usr/local/Homebrew/Library/Homebrew/build.rb:108:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:189:in `<main>'
```

**Comment by dogmaphobic** [comment]
Fixed in https://github.com/PX4/homebrew-px4/pull/23
